name: Run Playwright tests in CI

on:
  push:
    branches:
    - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies and run tests
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: export API_TOKEN=$API_TOKEN && npm install && npm test
